[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "taskgen-ai"
version = "3.3.4"
authors = [
  { name="John Tan Chong Min", email="tanchongmin@gmail.com" },
]
description = "TaskGen Simbian. A Task-based agentic framework building on StrictJSON outputs by LLM agents. Cybersecurity-focused version."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["openai>=1.3.6",
"langchain", "dill>=0.3.7", "termcolor>=2.3.0", "requests",
"PyPDF2", "python-docx", "pandas", "xlrd", "chromadb>=0.5.2",
"asyncio", "opentelemetry-sdk==1.22.0"]

[project.urls]
Homepage = "https://github.com/simbianai/taskgen"
Issues = "https://github.com/simbianai/taskgen/issues"